substitutions:
  name: evse-wallbox
  external_components_source: github://syssi/esphome-evse-wallbox@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:
  level: DEBUG

uart:
  id: uart0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: BOTH

modbus:
  id: modbus0
  uart_id: uart0
  send_wait_time: 0ms

evse_wallbox:
  id: evse0
  modbus_id: modbus0
  update_interval: 2s

# binary_sensor:
#   - platform: evse_wallbox
#     output:
#       name: "${name} output"

# sensor:
#   - platform: evse_wallbox
#     output_voltage:
#       name: "${name} output voltage"
